### ISSUE TITLE
Fail to up thorntail

### ISSUE THREAD

**Issue by jackynguyen93** [desmax74/openshift-drools-hacep#8]
I follow the guide but fail to up thorntail pods:
![image](https://user-images.githubusercontent.com/14976555/63665021-9c9c9a80-c7f3-11e9-860e-15e3cdee5489.png)

Please help me to resolve this

**Comment by desmax74** [comment]
I can't reproduce, here my log https://pastebin.com/rtcUd1AS
Which minishift config are you using ? 
Have you tried these openshift /strimzi setup ? 
- ubuntu: https://github.com/desmax74/openshift-handbook/blob/master/ubuntu/kafka_0121.md
-  fedora: https://github.com/desmax74/openshift-handbook/blob/master/fedora/kafka_0121.md

**Comment by jackynguyen93** [comment]
@desmax74 : I'm using oc 3.9 on Windows with strimzi, is it affect to this ?

**Comment by jackynguyen93** [comment]
I tried to use oc 3.11 on Ubuntu but it got the same issue. 
Do we need to do any other step before deploy thorntail

**Comment by jackynguyen93** [comment]
@desmax74 this is more about this error, any hint from this clue
![image](https://user-images.githubusercontent.com/14976555/63738193-3d05c400-c8b3-11e9-80da-b332ce6ae855.png)

**Comment by jackynguyen93** [comment]
After change maven build to this, now it's work
![image](https://user-images.githubusercontent.com/14976555/63749018-b5c94800-c8d4-11e9-8976-76c3231a26ea.png)
But now I stuck at sample client, do we need to export route for kafka-bootstrap
`   props.put("bootstrap.servers", "my-cluster-kafka-bootstrap-my-kafka-project.10.0.75.2.nip.io:443");`

**Comment by desmax74** [comment]
@jackynguyen93 let me know if: springboot and jdkhttp modules shows the same problem, how do you have installed docker on ubuntu if the problem seems the same for you, about the bpptstrap servers, are exposed automatically, the procedure to isntall strimzi is here:https://github.com/desmax74/openshift-handbook/blob/master/ubuntu/kafka_0121.md

**Comment by jackynguyen93** [comment]
@desmax74 sprintboot and jdkhttp is running well without this proplem.
Boostrap server seems not expose by default, can we expose it manually
![image](https://user-images.githubusercontent.com/14976555/63750249-4ef95e00-c8d7-11e9-9eba-68d048d121c2.png)

**Comment by desmax74** [comment]
The endpoint is in the routes section, have you run the command :
`oc expose service  openshift-kie-thorntail`

**Comment by jackynguyen93** [comment]
Yes, I did. You can see in the picture, the route is already exposed but when it show no application

**Comment by desmax74** [comment]
In the screenshot I see the applications not the routes

**Comment by desmax74** [comment]
Which is the result of 'oc get route' ?

**Comment by jackynguyen93** [comment]
@desmax74 
![image](https://user-images.githubusercontent.com/14976555/63754611-5fadd200-c8df-11e9-9a2b-f296066292f3.png)

**Comment by desmax74** [comment]
ok, let me know the results of http://openshift-kie-jdkhttp-myproject.10.0.75.2.nip.io/env/all  http://openshift-kie-springboot-myproject.10.0.75.2.nip.io/env/all and http://openshift-kie-thorntail-myproject.10.0.75.2.nip.io/env/all to see if a rest annotation/configuration is broken

**Comment by jackynguyen93** [comment]
jdkhttp
![image](https://user-images.githubusercontent.com/14976555/63755273-84ef1000-c8e0-11e9-8b4d-aeb2719c88de.png)

springboot
![image](https://user-images.githubusercontent.com/14976555/63755297-9506ef80-c8e0-11e9-8d0d-5590c8b19a6d.png)

thorntail
![image](https://user-images.githubusercontent.com/14976555/63755317-a0f2b180-c8e0-11e9-95de-f38094a61071.png)

**Comment by desmax74** [comment]
Ok, I'll check the thorntail module to fix the rest problem

**Comment by jackynguyen93** [comment]
Thanks @desmax74 , but how about boostrap server ? It seems the route for `my-cluster-kafka-bootstrap-my-kafka-project.10.0.75.2.nip.io:9092` doesn't exist

**Comment by desmax74** [comment]
Have you used this guide https://github.com/desmax74/openshift-handbook/blob/master/ubuntu/kafka_0121.md ? The strimzi files are changed to enable the external route on https to use from the clients

**Comment by jackynguyen93** [comment]
I follow your setup and now I can get route of boostrap server
![image](https://user-images.githubusercontent.com/14976555/63764052-2762bf80-c8f0-11e9-8cfd-d78b305eb29d.png)
But when run client sample I got the error  No resolvable bootstrap urls given in bootstrap.servers
Is my code correct?
![image](https://user-images.githubusercontent.com/14976555/63764124-537e4080-c8f0-11e9-97c1-f060f3732b41.png)

**Comment by desmax74** [comment]
The code seems correct, but remove the "9094" and replace with 443

**Comment by jackynguyen93** [comment]
![image](https://user-images.githubusercontent.com/14976555/63820685-62a6d200-c974-11e9-9be0-a91738ef3903.png)
@desmax74  still no resolvable

**Comment by jackynguyen93** [comment]
After some debugs I can make it work by put the properties to consumer.properties. But when run this, it shows some WARNs without any result. Do I miss somethings?
![image](https://user-images.githubusercontent.com/14976555/63831580-1c179e80-c999-11e9-83ae-f248350c7d08.png)

**Comment by desmax74** [comment]
Wait, the consumer is for internal use the demo use a producer, move the values form the consumer.properties into the ClientProducerDemo.getProperties , the client produce events in the events topic and you will see in the pods log the events processed by the leader and then by the replicas

**Comment by jackynguyen93** [comment]
@desmax74 As I posted, if we put properties in ClientProducerDemo.getProperties, the Kafka fail to construct `No resolvable bootstrap urls given in bootstrap.servers`
But it work if put to consumer.properties (because it reads default properties config file), so maybe the properties from ClientProducerDemo is not passed to Kafka construction.

About the pods log, could you give me a snapshot. I expect to see the log of drl file `System.out.println("Average price for " + $name + " is " + $avg);` somewhere

**Comment by jackynguyen93** [comment]
Thanks @desmax74 I see the log in springboot pod now.
The last question from me, can hacep support for a dynamic rule?. I means that we will build drl files at runtime and then update the current session with the new logic from new drl files.

**Comment by desmax74** [comment]
Hacep doesn't support yet the dynamic rule, currently you have to put your rules in the sample-hacep-project-kjar build and deploy in the pods, in the next releases you will see the dynamic rules.

**Comment by jackynguyen93** [comment]
Ok, I'm looking for this feature. Thank you so much. Close here.

**Comment by desmax74** [comment]
@jackynguyen93 https://github.com/kiegroup/openshift-drools-hacep/pull/31
